In [6]:
from turtle import st
import numpy as np

A = np.arange(101,122,1,dtype=int)
print(str(A).split('[')[1].split(']')[0].replace(' ','\',\''))
# 将A列表中的元素转化为字符串类型
['101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121',]


101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118
','119','120','121


In [2]:
# 设计一个数据结构 
channelList = ['101','102','103']
channelListUnits = ['V','V','V']
channelListResults = [['0.000','0.000','0.000'],['0.000','0.000','0.000'],['0.000','0.000','0.000']]

# 拼接到同一个字典
channelListDict = {
    channelList[i]:{
        'unit':channelListUnits[i],
        'result':channelListResults[i],
        'max':None,
    } for i in range(len(channelList))
}

print(channelListDict)

{'101': {'unit': 'V', 'result': ['0.000', '0.000', '0.000'], 'max': None}, '102': {'unit': 'V', 'result': ['0.000', '0.000', '0.000'], 'max': None}, '103': {'unit': 'V', 'result': ['0.000', '0.000', '0.000'], 'max': None}}


In [5]:
channelListDict = {
    'channelName':{
        'data':[],
        'unit':'',
        'type':'',
        'maxValue':'',
        'minValue':'',
    }
}

channelList = ['101','102','103']
channelListUnits = ['C','C','C']
channelListResults = [
                      ['1.000','2.000','3.000'],
                      ['4.000','5.000','6.000'],
                      ['7.000','8.000','9.000']
                      ]

# 将数据写入字典
for i in range(len(channelList)):
    channelListDict[channelList[i]] = {
        'data':channelListResults[i],
        'unit':channelListUnits[i],
        'type':['rtd-4w','rtd-4w','rtd-4w'],
        'maxValue':max(channelListResults[i]),
        'minValue':min(channelListResults[i]),
    }

for k,v in channelListDict.items():
    print(k,v)

channelName {'data': [], 'unit': '', 'type': '', 'maxValue': '', 'minValue': ''}
101 {'data': ['1.000', '2.000', '3.000'], 'unit': 'C', 'type': ['rtd-4w', 'rtd-4w', 'rtd-4w'], 'maxValue': '3.000', 'minValue': '1.000'}
102 {'data': ['4.000', '5.000', '6.000'], 'unit': 'C', 'type': ['rtd-4w', 'rtd-4w', 'rtd-4w'], 'maxValue': '6.000', 'minValue': '4.000'}
103 {'data': ['7.000', '8.000', '9.000'], 'unit': 'C', 'type': ['rtd-4w', 'rtd-4w', 'rtd-4w'], 'maxValue': '9.000', 'minValue': '7.000'}


In [1]:
# m = 2
# n = 3

# # 生成一个m*n的列表
# data = [[]*n]*m
# print(data)
import numpy as np
lst = []
dic = { 1: 
        ['1.000','2.000','3.000','10'],
        2:
        ['4.000','5.000','6.000','20'],
        3:
        ['7.000','8.000','9.000','30']
    }
keylst = list(dic.keys())

newData = np.array([1,2,3]).tolist(),
# newData =np.array(newData).T.tolist()
print(newData)
# 将newData中的元素按行添加到data中
for i in range(len(newData)):
    dic[keylst[i]].append(newData[i])
print(dic)


([1, 2, 3],)
{1: ['1.000', '2.000', '3.000', '10', [1, 2, 3]], 2: ['4.000', '5.000', '6.000', '20'], 3: ['7.000', '8.000', '9.000', '30']}


In [12]:
lst = "301:305,306,307,308"
parts = lst.split(',')

for part in reversed(parts):
    print(part)
    if ':' in part:
        start, end = part.split(':')
        parts.remove(part)
        new_part = [int(start) + i for i in range(int(end) - int(start) + 1)] 
        parts += [x for x in new_part]
    else:
        parts.append(int(part))
        parts.remove(part)
parts.sort()
print(parts)

308
307
306
301:305
[301, 302, 303, 304, 305, 306, 307, 308]


In [8]:
def transString(channelList,unitList):
    # 定义一个空列表，用于存放最终结果
    channelResult = []
    unitResult = []
    # 用 , 或 : 分割字符串
    channelParts = channelList.split(",")
    # unitParts = unitList.split(",")
    # 如果存在空字符串，则删除
    if "" in channelParts:
        channelParts.remove("")
        # unitParts.remove("")
    partsLength = len(channelParts)
    # 遍历分割后的列表
    for i in range(partsLength):
        # 如果包含 : ，则表示是连续的数字
        if ":" in channelParts[i]:
            # 用 : 分割数字，并转换为整数
            start, end = channelParts[i].split(":")
            # 用 range() 函数生成连续的数字，并添加到结果列表中
            channelResult.extend(range(int(start), int(end) + 1))
            unitResult.extend(unitList[i]*len(range(int(start), int(end) + 1)))
        else:
            # 否则，直接把数字转换为整数，并添加到结果列表中
            channelResult.append(int(channelParts[i]))
            unitResult.append(unitList[i])
    # 对结果列表进行排序
    # result.sort()
    # 打印结果列表
    # return str(channelResult).replace('[','').replace(']','')
    return channelResult, unitResult


# channelList = "306,301:305,307,308"
# unitList = ['C','F','mA','V']
channelList = "306,301:305,307,308,306"
unitList = ['C']*len(channelList.split(','))
a, b = transString(channelList, unitList)
print(a)
print(b)

[306, 301, 302, 303, 304, 305, 307, 308]
['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C']


In [13]:
from app.components.agilent34970a import Agilent34970A

channelList = "306,301:305,307,308"
unitList = ['C']*len(channelList.split(','))
a, b = Agilent34970A.transString(channelList, unitList)

channelList = '305'
unitList = ['K']
a, b = Agilent34970A.transString(channelList, unitList)

print(a)
print(b)

[305]
['K']


In [ ]:
channelList = "306,301:305,307,308"
unit = 'C'


In [4]:

x = []
print(x)
x.append(1)
print(x)

[]
[1]


In [5]:
l = [306, 301, 302, 303, 304, 305, 307, 308]
sep = ','
st = sep.join(str(i) for i in l)
print(st)
print(type(st))

306,301,302,303,304,305,307,308
<class 'str'>


In [1]:
# 定义一个函数，用来将形如"308,305:307,302"的字符串转换为列表和单位
def parse_string(s):
    # 初始化一个空列表和空单位
    result = []
    unit = []
    # 按逗号分割字符串
    segments = s.split(",")
    # 遍历每个分割后的字符串
    for segment in segments:
        # 如果有冒号，表示是一个范围
        if ":" in segment:
            # 按冒号分割范围，并转换为整数
            start, end = map(int, segment.split(":"))
            # 将范围内的所有整数添加到结果列表中
            result.extend(range(start, end + 1))
            # 将范围内的所有单位添加到单位列表中
            unit.extend([end] * (end - start + 1))
        else:
            # 否则，表示是一个单个值，直接转换为整数并添加到结果列表中
            result.append(int(segment))
            # 将单个值的单位添加到单位列表中
            unit.append(int(segment))
    # 返回结果列表和单位列表
    return result, unit

# 定义一个函数，用来将新的通道和单位拼接到原通道字符串中
def append_string(old_s, new_s, new_u):
    # 如果原通道字符串为空，则直接返回新通道和单位
    if not old_s:
        return new_s, new_u
    # 否则，先将原通道字符串和新通道字符串转换为列表和单位
    old_result, old_unit = parse_string(old_s)
    new_result, new_unit = parse_string(new_s)
    # 遍历新通道列表和单位列表
    for i in range(len(new_result)):
        # 如果新通道已在原通道列表中，则不拼接，但是要更新单位
        if new_result[i] in old_result:
            index = old_result.index(new_result[i])
            old_unit[index] = new_unit[i]
        else:
            # 否则，将新通道和单位拼接到原通道列表和单位列表中
            old_result.append(new_result[i])
            old_unit.append(new_unit[i])
    # 将更新后的原通道列表和单位列表转换为字符串，并返回
    return ",".join(map(str, old_result)), ",".join(map(str, old_unit))

# 测试一下函数的效果
old_s = "308,305:307,302"
new_s = "101,102:104"
new_u = "V,A"
print(append_string(old_s, new_s, new_u))
# 输出：('308,305,306,307,302,101,102,103,104', 'K,C,C,C,F,V,A,A,A')


('308,305,306,307,302,101,102,103,104', '308,307,307,307,302,101,104,104,104')


输入字符串形如: "308,305:307,302"，表示一个列表[308,305,306,307,302]
输入与字符串对应的单位，如: "K,  C, F"，表示与上述列表对应的单位列表[K,  C,  C,  C,  F]

添加新的通道和单位时，拼接到原通道字符串，如添加101,102:104，对应单位为: V, A
拼接为: "308,305,306,307,302,101,102,103,104"
同时拼接单位，"K,  C,  C,  C,  F,  V, A, A, A"
如果原通道字符串为空或者新通道未出现在原通道列表中，则直接拼接
如果新通道已在原通道字符串中，则不拼接，但是要更新单位
如原通道字符串为: 308,305:307,302
新通道为: 306，单位为V，则不拼接通道，但更新306通道单位为: K,  C,  V,  C,  F
新通道为：310，单位为A，则执行斌姐通道拼接，拼接后为: 308,305，306，307,302,310，单位为: K,  C,  C,  C,  F,  A


In [3]:
# 定义一个函数，用来将形如"308,305:307,302"的字符串转换为列表和单位
def parse_string(s, u):
    # 初始化一个空列表和空单位
    result = []
    unit = []
    # 按逗号分割字符串
    segments = s.split(",")
    # 遍历每个分割后的字符串
    for segment in segments:
        # 如果有冒号，表示是一个范围
        if ":" in segment:
            # 按冒号分割范围，并转换为整数
            start, end = map(int, segment.split(":"))
            # 将范围内的所有整数添加到结果列表中
            result.extend(range(start, end + 1))
            # 将范围内的所有单位添加到单位列表中
            unit.extend([end] * (end - start + 1))
        else:
            # 否则，表示是一个单个值，直接转换为整数并添加到结果列表中
            result.append(int(segment))
            # 将单个值的单位添加到单位列表中
            unit.append(int(segment))
    # 返回结果列表和单位列表
    return result, unit

# 定义一个函数，用来将新的通道和单位拼接到原通道字符串中
def append_string(old_s, old_u, new_s, new_u):
    # 如果原通道字符串为空，则直接返回新通道和单位
    if not old_s:
        return new_s, new_u
    # 否则，先将原通道字符串和新通道字符串转换为列表和单位
    old_result, old_unit = parse_string(old_s)
    new_result, new_unit = parse_string(new_s)
    # 遍历新通道列表和单位列表
    for i in range(len(new_result)):
        # 如果新通道已在原通道列表中，则不拼接，但是要更新单位
        if new_result[i] in old_result:
            index = old_result.index(new_result[i])
            old_unit[index] = new_unit[i]
        else:
            # 否则，将新通道和单位拼接到原通道列表和单位列表中
            old_result.append(new_result[i])
            old_unit.append(new_unit[i])
    # 将更新后的原通道列表和单位列表转换为字符串，并返回
    return ",".join(map(str, old_result)), ",".join(map(str, old_unit))

# 测试一下函数的效果
old_s = "308,305:307,302"
old_u = "K,C,F"
print(parse_string(old_s))
new_s = "306"
new_u = "V"
print(append_string(old_s, old_u, new_s, new_u))
# 输出：('308,305,306,307,302', 'K,C,V,C,F')


TypeError: parse_string() missing 1 required positional argument: 'u'

In [ ]:
def transString(self):
    channelListStr = self.channelListStr
    unitList = self.unitsList
    typeList = self.physicalType
    # 定义一个空列表，用于存放最终结果
    channelResult = []
    unitResult = []
    typeResult = []
    # 用 , 或 : 分割字符串,
    channelParts = channelListStr.split(",")
    # 如果存在空字符串，则删除
    if "" in channelParts:
        channelParts.remove("")
        # unitParts.remove("")
    partsLength = len(channelParts)
    # 遍历分割后的列表
    for i in range(partsLength):
        # 如果包含 : ，则表示是连续的数字
        if ":" in channelParts[i]:
            # 用 : 分割数字，并转换为整数
            start, end = channelParts[i].split(":")
            # 用 range() 函数生成连续的数字，并添加到结果列表中
            channelResult.extend(range(int(start), int(end) + 1))
            unitResult.extend([unitList[i]]*len(range(int(start), int(end) + 1)))
            typeResult.extend([typeList[i]]*len(range(int(start), int(end) + 1)))
        else:
            # 否则，添加到结果列表中
            channelResult.append(int(channelParts[i]))
            unitResult.append(unitList[i])
            typeResult.append(typeList[i])
    # 对结果列表进行排序
    # result.sort()
    # 打印结果列表
    # return str(channelResult).replace('[','').replace(']','')
    # return channelResult, unitResult, typeResult
    # self.channelList
    for i in range(len(channelResult)):
        self.channelListDict[channelResult[i]] = {
            'data':[],
            'unit':unitResult[i],
            'time':[],
            'type':typeResult[i],
            'maxValue':0,
            'minValue':0,
        }
    self.channelListDict = dict(sorted(self.channelListDict.items(), key=lambda x: x[0], reverse=False))
    sep = ','
    self.channelListStr = sep.join(str(k) for k in self.channelListDict.keys())
    self.channelList = list(self.channelListDict.keys())



In [1]:
d = {
    301:'123',
    302:'456',
}
for k, v in d.items():
    print(k,v)
    

301 123
302 456


In [1]:
import time
from func_timeout import func_set_timeout
import func_timeout
 
@func_set_timeout(5)
def timer():
    for num in range(1,11):
        time.sleep(1)
        print(num)
 
try:
    timer()
except func_timeout.exceptions.FunctionTimedOut as e:
    print(e)
    print("Time out!!!")


1
2
3
4
Function timer (args=()) (kwargs={}) timed out after 5.000000 seconds.

Time out!!!


In [2]:
import time
print(time.time())

1693070124.524605


In [29]:
class ABC(object):
    # a = 10
    def __init__(self):
        self.a = 20
        self.b = 30
    def test(self):
        return('test')
        ...
    def test2(self):
        return('test2')
        ...
    def get_test_var(self):
        return('get_test_var')
        ...

    # def getClassVar(self):
    #     return self.get_class_var()

a = ABC()
# print(getattr(a,'a'))
di = a.__dir__()
print(di)
t = (d for d in di if 'test' in d)
# print(t)
tt = list(method for method in a.__dir__() if 'test' in method)
print(tt)
for i in tt:
    print(getattr(a,i)())

['a', 'b', '__module__', '__init__', 'test', 'test2', 'get_test_var', '__dict__', '__weakref__', '__doc__', '__repr__', '__hash__', '__str__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__new__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']
['test', 'test2', 'get_test_var']
test
test2
get_test_var


In [3]:
colorList = ['#e6194B', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#42d4f4', '#f032e6', '#bfef45', '#fabed4', '#469990', '#dcbeff', '#9A6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#a9a9a9', '#ffffff', '#000000']
print(len(colorList))
# 将列表转换为生成器
colorList = (color for color in colorList)
print(colorList)
print(next(colorList))

22
<generator object <genexpr> at 0x00000170E0A85510>
#e6194B


In [6]:
with open('data.json', 'r') as f:
    data = f.read()

# print(data)
import json
import numpy as np
data = json.loads(data)

for k,v in data.items():
    data = np.array(v['data'])
    time = np.array(v['time'])-v['time'][0]

print(data)
print(time)

[ 2.120e-08 -1.695e-07  6.360e-08  0.000e+00 -1.271e-07 -1.483e-07
 -8.470e-08 -6.360e-08 -1.695e-07 -8.470e-08 -8.470e-08 -4.240e-08
 -1.483e-07 -4.240e-08 -6.360e-08]
[ 0.  2.  4.  6.  8.  9. 11. 13. 14. 16. 18. 20. 21. 23. 25.]


In [17]:
import datetime
import time
time0 = '2023,08,27,15,30,13.969'
# 转化为时间戳
# print(time.strptime.__doc__)
# timeArray = time.strptime(time0, f"%Y,%m,%d,%H,%M,%S.%f")
timeStamp = datetime.datetime.strptime(time0, f"%Y,%m,%d,%H,%M,%S.%f").timestamp()
# timeStamp = int(time.mktime(timeArray))
print(timeStamp)

1693121413.969


In [18]:
lst = np.array(['+2.64480000E+01','2023,08,27,15,42,52.583','-9.90000000E+37','2023,08,27,15,42,52.656'])

# 将lst分为两个数组，一个是时间，一个是数据
time = lst[1::2]
data = lst[::2]

print(time)
print(data)

['2023,08,27,15,42,52.583' '2023,08,27,15,42,52.656']
['+2.64480000E+01' '-9.90000000E+37']


In [67]:
data = [
  2.9291e+01,  2.0230e+03,  8.0000e+00,  2.7000e+01,  1.7000e+01,  3.5000e+01,
  4.1816e+01, -9.9000e+37,  2.0230e+03,  8.0000e+00,  2.7000e+01,  1.7000e+01,
  3.5000e+01,  4.1889e+01, -9.9000e+37,  2.0230e+03,  8.0000e+00,  2.7000e+01,
  1.7000e+01,  3.5000e+01,  4.1961e+01,  9.9000e+37,  2.0230e+03,  8.0000e+00,
  2.7000e+01,  1.7000e+01,  3.5000e+01,  4.2034e+01]
data = np.array(data).reshape(-1,7)
# 截取data中2-7位的数据作为时间
time0 = data[:, 1:]
# print(time0)
for i in time0:
    print(i)
    sep = ','
    i = sep.join(str(j) for j in i)
    strTime = datetime.datetime.strptime(i, f"%Y.0,%m.0,%d.0,%H.0,%M.0,%S.%f").timestamp()
    print(strTime)
result = data[:, 0]


[[2023.       8.      27.      17.      35.      41.816]
 [2023.       8.      27.      17.      35.      41.889]
 [2023.       8.      27.      17.      35.      41.961]
 [2023.       8.      27.      17.      35.      42.034]]
[2023.       8.      27.      17.      35.      41.816]
1693128941.816
[2023.       8.      27.      17.      35.      41.889]
1693128941.889
[2023.       8.      27.      17.      35.      41.961]
1693128941.961
[2023.       8.      27.      17.      35.      42.034]
1693128942.034


In [65]:
lst = [ 3.0652e+01,  2.0230e+03 , 8.0000e+00 , 2.7000e+01,  2.2000e+01 , 3.9000e+01,
  4.0314e+01, -9.9000e+37 , 2.0230e+03 , 8.0000e+00,  2.7000e+01 , 2.2000e+01,
  3.9000e+01,  4.0387e+01, -9.9000e+37,  2.0230e+03,  8.0000e+00 , 2.7000e+01,
  2.2000e+01,  3.9000e+01 , 4.0460e+01]
j=0
for i in range(3):
    print(lst[j:j+7][0])
    print(lst[j:j+7][1:])
    j+=7

# print('a','1',2)

30.652
[2023.0, 8.0, 27.0, 22.0, 39.0, 40.314]
-9.9e+37
[2023.0, 8.0, 27.0, 22.0, 39.0, 40.387]
-9.9e+37
[2023.0, 8.0, 27.0, 22.0, 39.0, 40.46]


In [69]:

# 使用 defaultdict 和 list comprehension 进行分组
my_dict = {'apple': 3, 'banana': 2, 'orange': 3, 'pear': 1, 'kiwi': 2}

from collections import defaultdict
grouped_dict = defaultdict(list)
for key, value in my_dict.items():
    grouped_dict[value].append(key)
# 输出分组后的字典
print(grouped_dict)

defaultdict(<class 'list'>, {3: ['apple', 'orange'], 2: ['banana', 'kiwi'], 1: ['pear']})


In [81]:
from itertools import groupby
from operator import itemgetter
import copy

dic = {
            1: {"name": 'tom', "age": 1}, 
            2: {"name": "jack", "age": 12}, 
            3: {"name": "lily", "age": 12}
        }
# dic = {
#     {"name": 'tom', "age": 1},
#     {"name": "jack", "age": 12},
#     {"name": "lily", "age": 12},
#     {"name": "lily", "age": 12},
# }

# for date, items in groupby(sorted(dic, key=itemgetter('age')), key=itemgetter('age')):
#     items = copy.deepcopy(items)
#     print(date,list(items))

for i in range(len(dic)):
    for date, items in groupby(sorted(dic[i+1], key=itemgetter('age')), key=itemgetter('age')):
        items = copy.deepcopy(items)
        print(date,list(items))
    # print(i)


TypeError: string indices must be integers

In [82]:
# 定义一个字典，存储姓名和年龄
# dic = {
#     1: {"name": 'tom', "age": 1}, 
#     2: {"name": "jack", "age": 12}, 
#     3: {"name": "lily", "age": 12}
# }
with open('1.json', 'r',encoding='utf-8') as f:
    dic = json.load(f)

# 定义一个空列表，用来存储分组后的结果
result = []

# 定义一个空集合，用来存储已经分组过的年龄
ages = set()

# 遍历字典中的每一项
for key, value in dic.items():
    # 获取当前项的姓名和年龄
    # physicalType = value["type"]
    # unit = value["unit"]
    # data = value["data"]
    # time = value["time"]
    name = value["name"]
    age = value["age"]
    
    # 如果当前年龄已经在集合中，说明已经分组过，跳过这一项
    if age in ages:
        continue
    
    # 否则，将当前年龄添加到集合中
    ages.add(age)
    
    # 定义一个空列表，用来存储当前年龄的所有项
    group = []
    
    # 再次遍历字典中的每一项
    for k, v in dic.items():
        # 如果当前项的年龄和之前的年龄相同，将其添加到列表中
        if v["age"] == age:
            group.append([k, v["name"], v["age"]])
    
    # 将当前年龄的列表添加到结果列表中
    result.append(group)

# 打印结果列表
print(result)


[[[1, 'tom', 1]], [[2, 'jack', 12], [3, 'lily', 12]]]


In [8]:
# 定义一个字典，存储温度数据
# dic = {
#     "305": {
#         "data": [
#             30.583,
#             30.589,
#             30.593,
#             30.595,
#             30.6,
#             30.6,
#             30.601,
#             30.602,
#             30.606,
#             30.609,
#             30.609,
#             30.607
#         ],
#         "type": "温度",
#         "unit": "C",
#         "time": [
#             1693152392.458,
#             1693152393.744,
#             1693152395.038,
#             1693152396.33,
#             1693152397.615,
#             1693152398.91,
#             1693152400.205,
#             1693152401.509,
#             1693152402.806,
#             1693152404.098,
#             1693152405.381,
#             1693152406.685
#         ],
#         "maxValue": 30.609,
#         "minValue": 30.583
#     },
#     "306": {
#         "data": [
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37,
#             -9.9e+37
#         ],
#         "type": "温度",
#         "unit": "C",
#         "time": [
#             1693152392.529,
#             1693152393.815,
#             1693152395.108,
#             1693152396.401,
#             1693152397.686,
#             1693152398.981,
#             1693152400.276,
#             1693152401.58,
#             1693152402.877,
#             1693152404.168,
#             1693152405.452,
#             1693152406.756
#         ],
#         "maxValue": -9.9e+37,
#         "minValue": -9.9e+37
#     }
# }
import json
with open('1.json', 'r',encoding='utf-8') as f:
    dic = json.load(f)

# 定义一个空字典，用来存储按照type分组后的结果
result = {}

# 遍历字典中的每一项
for key, value in dic.items():
    # 获取当前项的类型，数据，单位和时间
    type = value["type"]
    data = value["data"]
    unit = value["unit"]
    time = value["time"]
    
    # 如果当前类型已经在结果字典中，说明已经分组过，将当前项添加到对应的列表中
    if type in result:
        result[type].append({"channel": key, "unit": unit, "data": data, "time": time})
    
    # 否则，将当前类型作为一个新的键，创建一个空列表作为值，并将当前项添加到列表中
    else:
        result[type] = [{"channel": key, "unit": unit, "data": data, "time": time}]

# 打印结果字典
for k,v in result.items():
    print(k)
    # for d in v:
    #     print(i)
    for i in range(len(v)):
        print(v[i]['channel'],v[i]['unit'],v[i]['data'],v[i]['time'])
    


温度
305 C [30.583, 30.589, 30.593, 30.595, 30.6, 30.6, 30.601, 30.602, 30.606, 30.609, 30.609, 30.607] [1693152392.458, 1693152393.744, 1693152395.038, 1693152396.33, 1693152397.615, 1693152398.91, 1693152400.205, 1693152401.509, 1693152402.806, 1693152404.098, 1693152405.381, 1693152406.685]
306 C [-9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37] [1693152392.529, 1693152393.815, 1693152395.108, 1693152396.401, 1693152397.686, 1693152398.981, 1693152400.276, 1693152401.58, 1693152402.877, 1693152404.168, 1693152405.452, 1693152406.756]
流量
307 ma [9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37] [1693152392.6, 1693152393.887, 1693152395.18, 1693152396.473, 1693152397.757, 1693152399.053, 1693152400.347, 1693152401.651, 1693152402.948, 1693152404.24, 1693152405.523, 1693152406.828]


In [ ]:
{'温度': [
    {'channel': '305', 'unit': 'C', 'data': [30.583, 30.589, 30.593, 30.595, 30.6, 30.6, 30.601, 30.602, 30.606, 30.609, 30.609, 30.607], 'time': [1693152392.458, 1693152393.744, 1693152395.038, 1693152396.33, 1693152397.615, 1693152398.91, 1693152400.205, 1693152401.509, 1693152402.806, 1693152404.098, 1693152405.381, 1693152406.685]}, 
    {'channel': '306', 'unit': 'C', 'data': [-9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37], 'time': [1693152392.529,1693152393.815, 1693152395.108, 1693152396.401, 1693152397.686, 1693152398.981, 1693152400.276, 1693152401.58, 1693152402.877, 1693152404.168, 1693152405.452, 1693152406.756]}, 
    {'channel': '307', 'unit': 'C', 'data': [9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37, 9.9e+37, -9.9e+37, -9.9e+37, -9.9e+37], 'time': [1693152392.6, 1693152393.887, 1693152395.18, 1693152396.473, 1693152397.757, 1693152399.053, 1693152400.347, 1693152401.651, 1693152402.948, 1693152404.24, 1693152405.523, 1693152406.828]}
    ]
}


In [9]:
print(len([{'channel': 305, 'unit': 'C', 'data': [29.667, 29.691], 'time': [1693158772.332, 1693158773.476]}]))

1


In [11]:
import numpy as np

lst = [1693198574.578, 1693198576.709, 1693198578.26, 1693198580.055, 1693198581.64, 1693198583.225, 1693198584.804, 1693198586.4, 1693198587.983, 1693198589.563, 1693198591.144, 1693198592.72, 1693198594.302, 1693198595.878, 1693198597.459, 1693198599.041, 1693198600.616]

lst = np.array(lst)-lst[0]

print(lst)

[ 0.          2.13100004  3.68199992  5.477       7.06200004  8.64699984
 10.22599983 11.82200003 13.40499997 14.9849999  16.56599998 18.14199996
 19.72399998 21.29999995 22.88100004 24.46299982 26.03799987]


In [13]:
a = [ 2.7580e+01, 2.0230e+03  ,8.0000e+00  ,2.8000e+01  ,1.7000e+01 , 1.0000e+01,
  4.2829e+01,  3.0500e+02 , 9.9000e+37 , 2.0230e+03,  8.0000e+00 , 2.8000e+01,
  1.7000e+01,  1.0000e+01 , 4.2896e+01 , 3.0600e+02 ,-9.9000e+37 , 2.0230e+03,
  8.0000e+00,  2.8000e+01,  1.7000e+01 , 1.0000e+01  ,4.2964e+01 , 3.0700e+02,
  9.9000e+37,  2.0230e+03 , 8.0000e+00 , 2.8000e+01 , 1.7000e+01 , 1.0000e+01,
  4.3031e+01,  3.0800e+02]

print((a))

[27.58, 2023.0, 8.0, 28.0, 17.0, 10.0, 42.829, 305.0, 9.9e+37, 2023.0, 8.0, 28.0, 17.0, 10.0, 42.896, 306.0, -9.9e+37, 2023.0, 8.0, 28.0, 17.0, 10.0, 42.964, 307.0, 9.9e+37, 2023.0, 8.0, 28.0, 17.0, 10.0, 43.031, 308.0]


In [23]:
dic = {'温度': [
    {'channel': 305, 'unit': 'C', 'data': [], 'time': []},{'channel': 306, 'unit': 'C', 'data': [], 'time': []}
    ]
    }
# 获取所有的通道号，尽量避免循环 
channelList = []
for k,v in dic.items():
    for i in range(len(v)):
        channelList.append(v[i]['channel'])

print(channelList)

[305, 306]


In [37]:
transPara = None

channelListDict = {
    'data':[],
    'time':[],
    'maxValue':0,
    'minValue':0,
    'transPara':transPara
,
}

print(channelListDict)
if channelListDict['transPara']:
    print(0)

{'data': [], 'time': [], 'maxValue': 0, 'minValue': 0, 'transPara': None}


这个程序使用了正则表达式来匹配合法的格式，它是一种用于描述字符串模式的语言。这个正则表达式的含义是：

^ 表示字符串的开始
(\d+) 表示一个或多个数字，用括号括起来表示一个捕获组
(,\d+)* 表示零个或多个逗号后跟一个或多个数字，用括号括起来表示一个捕获组，并用星号表示重复零次或多次
(:\d+)? 表示可选的冒号后跟一个或多个数字，用括号括起来表示一个捕获组，并用问号表示重复零次或一次
$ 表示字符串的结束

In [68]:
import re

def validate_input(input_str):
    # 检验输入值的格式是否合法
    # 合法的格式是形如"301,302,305:308"的字符串，每一个数字之间使用半角,或者:进行区分, 数字位数为3位, 首位数字为1-3, 后两位数字不超过23
    # 冒号连接的两个数字首位必须一致
    # 不合法的格式是形如"301，302"或"23,26"的字符串，使用全角或者没有使用:
    # 使用正则表达式来匹配合法的格式
    # 返回True或False
    pattern = r'^[1-3][0-9][0-9]([,|:][1-3][0-9][0-9])*$'
    return re.match(pattern, input_str) is not None

print(validate_input('301,302,305,308'))

True


In [10]:
s = 'hell-o'
print(s.split(',')[0])

hell-o


In [7]:
import configparser
import os

from loguru import logger


# class ConfigImport():
    
#     def __init__(self, flieName):
#         self.fileName = flieName
#         self.config = configparser.ConfigParser()
#         self.config.read(self.fileName, encoding='utf-8')
#         self.__initConfig()
        
#         ...
#     def parseConfig(self):
#         self.config.read(self.fileName, encoding='utf-8')
#         return self.__initConfig()
#         ...

class TemperatureConfig():
    probeType: str
    sensoType: str
    channelList: str
    temperatureUnit: str


class CurrentConfig():
    currType: str
    currRange: str
    channelList: str


class VotageConfig():
    ...


class CalculatedConfig():
    currType: str
    currRange: str
    channelList: str
    measureType: str
    measureUnits: str
    currRangeMin: float
    currRangeMax: float
    mesureRangeMin: float
    mesureRangeMax: float



class ConfigImport():
    configParseList = ['Temperature', 'Current', 'Votage', 'Calculated']
    temperatureConfig = TemperatureConfig()
    currentConfig = CurrentConfig()
    votageConfig = VotageConfig()
    calculatedConfig = CalculatedConfig()

    def __init__(self,fileName):
        self.fileName = fileName
        self.load_config()

    def load_config(self) -> None:
        if not os.path.exists(self.fileName):
            return '配置文件不存在'
        try:
            conf = configparser.RawConfigParser()
            conf.read(self.fileName,encoding="utf-8")
            sections = conf.sections()
            for section in sections:
                items = conf.items(section)
                for item in items:
                    if section in self.configParseList:
                        parse = eval('self.{}Config'.format(section))
                        setattr(parse, item[0], eval(item[1]))
            return("配置文件加载成功")
        except Exception as e:
            return f"配置文件加载失败{e}"

conf = ConfigImport(r'app/config/instConfig.ini')

print(conf.temperatureConfig.channelList)


AttributeError: 'TemperatureConfig' object has no attribute 'channelList'